### ISSUE TITLE
[Question] Disable crop and rotate in image upload dialog?

### ISSUE THREAD

**Issue by vfsoraki** [GetmeUK/ContentTools#544]
Is it possible?

I didn't find anything in documentations.

**Comment by anthonyjb** [comment]
Simplest solution for disabling tools in the image dialog is just to hide them with CSS, like so:

```css
.ct-control--crop,
.ct-control--rotate-cw,
.ct-control--rotate-ccw {
    display: none !important;
}
```

P.S sorry for the late reply.
