### ISSUE TITLE
Too general CSS selectors 

### ISSUE THREAD

**Issue by grsmv** [GetmeUK/ContentTools#92]
Guys, first of all - thank you for such amazing piece of work. It's really helpful to have such amazing thing in toolbox.

But right in [this CSS-rules](https://github.com/GetmeUK/ContentTools/blob/master/external/styles/_content-edit.scss#L355) I see really general style setting. Right now it can (and actually does) impact external styles at the web page. Is it possible to wrap those rules in something? Or apply them only for editable areas?

Thank you

**Comment by anthonyjb** [comment]
Hi @grsmv, thank you for the kind comments :)

ContentTools CSS (SASS) doesn't (shouldn't) apply any general styles, the [`ct-widget`](https://github.com/GetmeUK/ContentTools/blob/master/src/styles/ui/_ui.scss#L7) class is used as a wrapper to ensure general styles only impact elements with that class or children of elements with that class.

ContentEdit is a little different, most styles are only applied to elements with the [`ct-element`](https://github.com/GetmeUK/ContentEdit/blob/master/src/styles/content-edit.scss#L53) class however as you've highlighted there are some [defaults](https://github.com/GetmeUK/ContentEdit/blob/master/src/styles/content-edit.scss#L355) added to aid alignment of images, iframes and video blocks. These are provided because once the HTML is no longer editable the alignment of those elements still needs to be retained.

These are only defaults though and as per the comment it is expected that they will be removed / overridden by the site CSS. For example they can be reset using the following CSS at any point after including the ContentTools/Edit css.

```
img,
iframe,
video {
    display: initial;
    margin: initial;
}
```

**Comment by grsmv** [comment]
Thank you for clarification. But here's extraction from compiled CSS:
```css
/**
 * The alignment of elements such as images and videos horizontally is achieved
 * through the `align-left` and `align-right` classes. [...]
 */
img,
iframe,
video,
[data-ce-tag=img],
.ce-element--type-image,
.ce-element--type-video {
  display: block;
  margin-left: auto;
  margin-right: auto; }
```

which applies specific `display` and `margin` rules for *all* images (iframes and videos, which is less important) on the page. I believe that this is overgeneralization because this have unwanted impact on other elements at the page.

**Comment by anthonyjb** [comment]
Yes but if you compile the CSS yourself then you can remove that section (or use it and wrap it in a class that limits the scope to your own requirements), or simply reset the styles as per the example in my last comment.

The only alternatives that don't require a default like this (that I can think of at least) are to either:

- Have a requirement for editable areas, such as requiring editable regions to have the CSS class `ct-editable`.
- Applying a CSS class to all `images`, `iframes` and `videos` (along the lines `ct-image`) which remains against these elements once the document no longer editable. 
- Removing these rules and requiring users to implement them per their requirement with no default.

My preference is to retain the default though and allow anyone implementing the library to either modify the CSS/SASS for their requirements (and build themselves) or reset the styles if the wish not to and then implement there own, e.g:

```css
img,
iframe,
video {
    display: initial;
    margin: initial;
}

.editable img,
.editable iframe,
.editable video {
    display: block;
    margin-left: auto;
    margin-right: auto;
}

    .editable img.align-left,
    .editable iframe.align-left,
    .editable video.align-left {
        clear: initial;
        float: left;
    }

    .editable img.align-right,
    .editable iframe.align-right,
    .editable video.align-right {
        clear: initial;
        float: right;
    }
```

Where `editable` in this case is a CSS class applied to all elements that contain editable content.

I am open suggestions though if you can see a cleaner solution that still provides a default.
